workflow:
  version: 1
  signals:
    results:
      - Variable_name: string
  frames:
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: mysql-demo
          query: select Variable_name from sys.metrics
          output: [:results]
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :results # TrinoDemo takes a colleciton type
