workflow:
  version: 1
  signals:
    results:
      total_count: number
      incomplete_results: boolean
  frames:
    - frame:
      view:
        component: OTRestDataProvider
        props:
          _DEBUG_: true
          source: rest-demo
          # path: /search/issues?q=repo:{repo_nwo}+is:issue&per_page=1
          path: /search/issues?q=repo:open-truss/open-truss+is:issue&per_page=1
          method: GET
          output: [:results]
          headers: 
            User-Agent: open-truss-rest-demo
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :results
