workflow:
  version: 1
  signals:
    results:
      total_count: string
  frames:
    - frame:
      view:
        component: OTRestDataProvider
        props:
          source: rest-demo
          path: /search/issues?q=repo:{repo_nwo}+is:issue&per_page=1
          method: GET
          output: [:results]
          headers:
            - User-Agent: open-truss-rest-demo
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :results
