workflow:
  version: 1
  signals:
    r1:
      value: number[]
    r2:
      value: string[]
  frames:
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: trino-demo
          query: >
            SELECT ARRAY[ 1, NULL, 3 ] AS value
          output: [:r1]
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :r1
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: trino-demo
          query: >
            SELECT ARRAY[ 'one', NULL, 'three' ] AS value
          output: [:r2]
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :r2
