workflow:
  version: 1
  _DEBUG_: true
  signals:
    repoName: string
    repoOwner: string
    graphqlResults:
      repository:
        issues:
          totalCount: number
  frames:
    - frame:
      view:
        component: OTGraphqlDataProvider
        props:
          source: github-graphql-demo
          output: [:graphqlResults]
          headers:
            Content-Type: application/json
            User-Agent: open-truss-rest-demo
          body: >
            query($repoName: String!, $repoOwner: String!) {
              repository(name: $repoName, owner: $repoOwner) {
                issues(first: 1) {
                  totalCount
                }
              }
            }
          variables:
            repoName: :repoName
            repoOwner: :repoOwner
      frames:
        - frame:
          view:
            component: RepoNameOwnerInput
            props:
              repoName: :repoName
              repoOwner: :repoOwner
        - frame:
          view:
            component: DataDemo
            props:
              results: :graphqlResults
