workflow:
  version: 1
  signals:
    resultsArray: # OTUqiDataProvider returns collection with rows using the shape of the object
      - name: string
        phone: string
        acctbal: number
        comment: string
    resultsObject: # OTUqiDataProvider returns object grabbing the first row of results
      name: string
      phone: string
      acctbal: number
      comment: string
  frames:
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: trino-demo
          query: >
            SELECT name, phone, acctbal, comment
            FROM tpch.sf1.customer
            limit 10
          # output: [:resultsArray, :resultsObject, :name]
          resultsArray: :resultsArray
          resultsObject: :resultsObject
          output:
            resultsArray:
              - name: string
                phone: string
                acctbal: number
                comment: string
            resultsObject:
              name: string
              phone: string
              acctbal: number
              comment: string
      frames:
        - frame:
          view:
            component: DataDemo
            props:
              results: :resultsArray
        - frame:
          view:
            component: DataDemo
            props:
              results: :resultsObject
