workflow:
  version: 1
  signals:
    results: Records
  frames:
    - frame:
      view:
        component: OTUqiDataProvider
        props:
          source: trino-demo
          query: >
            SELECT 'Column', 'Type', 'Extra', 'Comment'
            FROM tpch.sf1.customer
            limit 10
          results: :results
          output:
            results:
              - Column: string
                Type: string
                Extra: string
                Comment: string
      frames:
        - frame:
          view:
            component: TrinoDemo
            props:
              results: :results # TrinoDemo takes a colleciton type
