workflow:
  version: 1
  frames:
    - frame:
      data: Foo (component from application)
      view:
        component: Foo
        props:
          color: blue
      frames:
        - frame:
          data: OTBar (component from OT package)
          view:
            component: OTBar
            props:
              color: blue
