#!/bin/bash
# Usage: script/server
# Ensures dependencies are installed and starts the dev server.

script_dir=$(dirname "$(readlink -f "$0")")
demo_app_dir=$(dirname "$script_dir")
root_dir=$(dirname "$demo_app_dir")
open_truss_package_dir="$root_dir/packages/open-truss"

script/bootstrap

# Build the open-truss package so dist/ is up to date
cd $open_truss_package_dir && npm run build && cd $demo_app_dir

echo "Starting Vite dev server..."
npm run dev
