#!/bin/bash

# Function to terminate both tsc processes
terminate_tsc_processes() {
  echo "Terminating TypeScript watch processes..."
  pkill -P $$
}

# Trap SIGINT and SIGTERM and call the function to terminate tsc processes
trap 'terminate_tsc_processes' SIGINT SIGTERM

echo "Running npm run tsc:watch"
(npm run tsc:watch) &

echo "Runing npm run dev"
(npm run start) &

wait
